#!/usr/bin/env python3

import sys

from functions import poll

def printUsage():
    print("USAGE")
    print("    ./209poll pSize sSize p\n")
    print("DESCRIPTION")
    print("    pSize  size of the population")
    print("    sSize  size of the sample (supposed to be representative)")
    print("    p      percentage of voting intentions for a specific candidate")

def start():
    ret = 0
    pSize = 0
    sSize = 0
    p = 0.0
    if len(sys.argv) == 2 and sys.argv[1] == "-h":
        printUsage()
        return (0)
    if len(sys.argv) != 4:
        print("Error, wrong number of arguments !", file=sys.stderr)
        return (84)
    try:
        pSize = int(sys.argv[1])
        sSize = int(sys.argv[2])
        p = float(sys.argv[3])
    except:
        print("Error, arguments must be numbers !")
        return (84)
    if sSize > pSize:
        print("sSize cannot be greater than pSize", file=sys.stderr)
        return (84)
    if pSize <= 0 or sSize <= 0:
        print("Error: pSize and sSize need to be positive", file=sys.stderr)
        return (84)
    ret = poll(pSize, sSize, p)
    return (ret)

if __name__ == "__main__":
    ret = start()
    exit(ret)
