##
## EPITECH PROJECT, 2018
## Makefile
## File description:
## Makefile
##


all:
	cp save_launcher.py groundhog
	chmod +x groundhog

clean:

fclean:	clean
	rm -f groundhog

re:	fclean all

.PHONY:	all	\
	re	\
	clean	\
	fclean