#!/usr/bin/php
<?php

include 'functions.php';

// function formula($x, $sigma, $micro) {
//     $expo = (-1 * pow($x - $micro, 2)) / (2 * pow($sigma, 2));
//     $res = exp($expo) / ($sigma * sqrt(2 * M_PI));
//     return ($res);
// }

// function inferiorCalc($u, $s, $iq1)
// {
//     $res = 0.0;

//     for ($i = 0 ; $i < $iq1 ; $i += 0.001) {
//         $res += formula($i, $s, $u);
//     }
//     printf("%.1f%% of people have an IQ inferior to %d\n", $res / 10, $iq1);
//     return (0);
// }

// function between($av) {
//     $i = intval($av[3]);
//     $res = 0;

//     while ($i <= intval($av[4])) {
//         $res += formul($i, intval($av[2]), intval($av[1]));
//         $i += 0.001;
//     }
//     printf("%.1f%% of people have an IQ between %d and %d\n", $res / 10, $av[3], $av[4]);
//     return 0;
// }

// function betweenCalc($u, $s, $iq1, $iq2)
// {
//     $res = 0.0;

//     for ($i = $iq1 ; $i < $iq2 ; $i += 0.001) {
//         $res += formula($i, $s, $u);
//     }
//     printf("%.1f%% of people have an IQ between %d and %d\n", $res / 10, $iq1, $iq2);
//     return (0);
// }

// function densityCalc($u, $s)
// {
//     $res = 0.0;

//     for ($i = 0; $i <= 200 ; $i++) {
//         $res = formula($i, $s, $u);
//         printf("%d %.5f\n", $i, $res);
//     }
//     return (0);
// }

// function is_int_number($arg, $arg_name)
// {
//     $int = intval($arg);
//     $float = floatval($arg);

//     if (is_numeric($arg) == FALSE) {
//         fprintf(STDERR, "Error $arg_name must a number !\n");
//         return (84);
//     }
//     if ($int != $float) {
//         fprintf(STDERR, "Error $arg_name must be an integer !\n");
//         return (84);
//     }
//     if ($int < 0) {
//         fprintf(STDERR, "Error $arg_name cannot be lower than 1 !\n");
//         return (84);
//     }
//     return (0);
// }

function printUsage()
{
    printf("USAGE\n");
    printf("    ./205IQ u s [IQ1] [IQ2]\n");
    printf("DESCRIPTION\n");
    printf("    u mean\n");
    printf("    s standard deviation\n");
    printf("    IQ1 minimum IQ\n");
    printf("    IQ2 maximum IQ\n");
}

function main($ac, $av)
{
    $u;
    $s;
    $iq1 = 0;
    $iq2 = 200;

    if ($ac == 2 && $av[1] == "-h") {
        printUsage();
    }
    if ($ac < 3 || $ac > 5) {
        fprintf(STDERR, "Wrong number of arguments !\n");
        return(84);
    }
    for ($i = 1; $i < $ac ; $i++) {
        if (is_int_number($av[$i], "arguments") == 84) {
            return (84);
        }
    }
    $u = intval($av[1]);
    if ($u > 200)
        return (84);
    $s = intval($av[2]);
    if ($ac >= 4) {
        $iq1 = intval($av[3]);
        if ($iq1 > 200)
            return (84);
        if ($ac == 4) {
            inferiorCalc($u, $s, $iq1);
            return (0);
        }
    }
    if ($ac == 5) {
        $iq2 = intval($av[4]);
        if ($iq2 < $iq1 || $iq2 > 200)
            return (84);
        betweenCalc($u, $s, $iq1, $iq2);
        return (0);
    }
    densityCalc($u, $s);
    return (0);
}

exit (main($argc, $argv));

?>