##
## EPITECH PROJECT, 2019
## PSU_my_ls_2018
## File description:
## makefile for th project
##

clean:
	make -sC ./tests clean

fclean:	clean
	make -sC ./tests fclean

tests_run:
		make -sC ./tests
		./tests/unit_tests

.PHONY:	clean	\
	fclean	\
	tests_run
